### PR TITLE
Adds Entra auth for CS postgres

### PR DESCRIPTION
**Pull request by markturansky**
Adds Entra authentication to CS deployment

### CODE REVIEW

**Comment by bennerv** [comment]
Since we don't have prow, no /hold label applies so moved into draft to prevent accidental merge.

**Comment by markturansky** [comment]
@geoberle @bennerv I've modified this and the deployment template to use the Workload ID param for postgres.  I'm specifically setting this workload ID as a new param to avoid conflict with the single secret creds we have today.

**Comment by miguelsorianod** [comment]
We can close this as it's been obsoleted by other changes.

We have rolled out changes to the P1 environment and we are currently running CS against postgresql Entra DB

**Pull request closed without merging**
